---
- name: Spack config externals
  shell: |
    module load openmpi
    {{ spack_dir }}/bin/spack external find --scope=system --not-buildable

- name: Spack mark cmake as buildable
  command: "{{ spack_dir }}/bin/spack config --scope system add packages:cmake:buildable:true"

- name: Spack mark python as buildable
  command: "{{ spack_dir }}/bin/spack config --scope system add packages:python:buildable:true"

- name: Spack mark OpenMPI as buildable
  command: "{{ spack_dir }}/bin/spack config --scope system add packages:openmpi:buildable:true"

- name: Spack mark GCC as buildable
  command: "{{ spack_dir }}/bin/spack config --scope system add packages:gcc:buildable:true"

- name: Spack Find DevTool compiler
  command: "{{ spack_dir }}/bin/spack compiler find --scope system /opt/rh/devtoolset-11/root/usr/bin"


- name: Add Spack to default shells
  copy:
    dest: /etc/profile.d/95-spack.sh
    content: |
      . {{ spack_dir }}/share/spack/setup-env.sh
    owner: root
    mode: 0755
    force: no
