---
- name: Upgrade PIP3
  pip:
    executable: pip3
    name: pip
    state: latest

- name: Install FE C&C Dependencies
  pip:
    executable: pip3
    name:
      - requests
      - pexpect
      - google-cloud-storage
      - google-cloud-pubsub

- name: Enable su to OS Login
  lineinfile:
    path: /etc/pam.d/su
    line: session    [success=ok default=ignore] pam_mkhomedir.so
    state: present
    insertafter: EOF

- name: Install FE C&C Daemon
  copy:
    src: ghpcfe_c2daemon.py
    dest: /usr/local/sbin/ghpcfe_c2daemon.py
    mode: 0755

- name: Install FE C&C Daemon Config
  template:
    src: ghpcfe_c2.yaml.j2
    dest: /usr/local/etc/ghpcfe_c2.yaml
    mode: 0755

- name: Install FE C&C service file
  copy:
    src: ghpcfe_c2.service
    dest: /etc/systemd/system/ghpcfe_c2.service

- name: Start FE C&C Daemon
  systemd:
    daemon_reload: yes
    state: started
    name: ghpcfe_c2
    enabled: yes
    masked: no
