---
- name: Upgrade PIP3
  pip:
    executable: pip3
    name: pip
    state: present

- name: Install FE C&C Dependencies
  shell: . /opt/rh/devtoolset-11/enable && pip3 install requests pexpect google-cloud-storage google-cloud-pubsub

- name: Install FE C&C Daemon
  copy:
    src: ghpcfe_c2daemon.py
    dest: /usr/local/sbin/ghpcfe_c2daemon.py
    mode: 0755

- name: Install FE C&C Daemon Config
  template:
    src: ghpcfe_c2.yaml.j2
    dest: /usr/local/etc/ghpcfe_c2.yaml
    mode: 0755

- name: Install FE C&C service file
  copy:
    src: ghpcfe_c2.service
    dest: /etc/systemd/system/ghpcfe_c2.service
    mode: 0644

- name: Start FE C&C Daemon
  systemd:
    daemon_reload: True
    state: started
    name: ghpcfe_c2
    enabled: True
    masked: False
