# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

blueprint_name: hpc-cluster-hybrid-v5

vars:
  project_id:  ## <<Project_B>>
  deployment_name: hybrid-config
  region: us-central1
  zone: us-central1-c
  static_controller_hostname:  ## <<instance name>>.c.<<Project_A>>.internal

deployment_groups:
- group: primary
  modules:
  - id: network1
    source: modules/network/pre-existing-vpc
    settings:
      network_name: compute-vpc-network
      subnetwork_name: primary-subnet

  - id: scratchfs
    source: modules/file-system/filestore
    use: [network1]
    settings:
      local_mount: /scratch

  - id: debug-partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use: [network1]
    settings:
      partition_name: debug
      node_count_dynamic_max: 10
      exclusive: false
      machine_type: n2-standard-2
      is_default: false

  - id: compute-partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    settings:
      partition_name: compute
      node_count_dynamic_max: 20

  - id: slurm-controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid
    use:
    - debug-partition
    - compute-partition
    - scratchfs
    settings:
      output_dir: ./hybrid
      slurm_bin_dir: /usr/local/bin
      slurm_control_host: $(vars.static_controller_hostname)
      install_dir: /etc/slurm/hybrid
