---
- name: Install CentOS Software Collections
  yum:
    name: centos-release-scl
- name: Install Dev Tools
  yum:
    name:
      - devtoolset-9
      - devtoolset-11
      - cmake
      - python2-devel
      - python36-devel


- name: Add DevTools to default shells
  copy:
    dest: /etc/profile.d/98-devtools.sh
    content: |
      . /opt/rh/devtoolset-11/enable
    owner: root
    mode: 0755
    force: no
