# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Ensure desktop is installed
  hosts: localhost
  become: true
  tasks:  
  - name: Install desktop packages
    ansible.builtin.apt:
      name:
      - xfce4
      - xfce4-goodies
      state: present
      update_cache: true

  - name: Fix headless Nvidia issue 
    ansible.builtin.shell:
      sudo nvidia-xconfig --query-gpu-info > /tmp/gpu-info.txt

      PCI_ID=$(cat /tmp/gpu-info.txt | grep "PCI BusID " | head -n 1 | cut -d':' -f2-99 | xargs)

      sudo nvidia-xconfig -a --allow-empty-initial-configuration --enable-all-gpus --virtual=1920x1200 --busid=$PCI_ID

      sudo sed -i '/Section "Device"/a \ \ \ \ Option\t"HardDPMS" "false"' /etc/X11/xorg.conf
