# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Ensure nvidia grid drivers and other binaries are installed
  hosts: localhost
  become: true
  tasks:      
  - name: Install binaries for GRID drivers
    ansible.builtin.apt:
      name:
      - build-essential
      - gdebi-core
      - mesa-utils
      - lightdm
      state: present
      update_cache: true
      
  - name: Download GPU driver
    ansible.builtin.get_url:
      url: https://storage.googleapis.com/nvidia-drivers-us-public/GRID/vGPU14.2/NVIDIA-Linux-x86_64-510.85.02-grid.run
      dest: /tmp/
      mode: "0755"
      
  - name: Install GPU driver
    ansible.builtin.shell: /tmp/NVIDIA-Linux-x86_64-510.85.02-grid.run -silent
  
  - name: Confirm GPU driver is installed
    ansible.builtin.shell: nvidia-smi
    register: nvidiasmi
  - debug: msg="{{ nvidiasmi.stdout }}"

  - name: Download VirtualGL driver
    ansible.builtin.get_url:
      url: https://sourceforge.net/projects/virtualgl/files/3.0.2/virtualgl_3.0.2_amd64.deb/download
      dest: /tmp/virtualgl_3.0.2_amd64.deb
      mode: "0755"
    
  - name: Install VirtualGL
    ansible.builtin.shell: sudo gdebi /tmp/virtualgl_3.0.2_amd64.deb --non-interactive
    
  - name: Confirm virtualgl installed DEBUG
    ansible.builtin.shell: sudo apt list --installed | grep virtualgl
    register: apt_list
  - debug: msg="{{ apt_list.stdout }}" 

  - name: Configure VirtualGL for X
    ansible.builtin.shell: sudo vglserver_config +glx +s +f -t

  - name: Register drivers with dkms
    ansible.builtin.shell: sudo systemctl set-default graphical.target

  - name: Configure lightdm for X
    ansible.builtin.shell:
      echo "/usr/sbin/lightdm" > /etc/X11/default-display-manager
      
      sudo DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm
      
      sudo systemctl unmask lightdm.service
      sudo systemctl daemon-reload
      sudo systemctl start lightdm
